### ISSUE TITLE
Add pre-submit tests

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/todos#11]
- [x] `go test` on Linux (#24)
- [x]  `go test` on Windows (#53 )
- [x]  `go test` on Mac OS (#49 )
- [x] `golangci-lint` (#24)
  - #28
  - #30
- [x] `markdownlint` (#24)
- [x] `yamllint` (#24)
- [x] `actionlint` (#54)
- [x] License header check (#42)
- [x] Code coverage (#35)
- [x] Google CLA
- [x] PR title conventional commits (#50)
