### ISSUE TITLE
More supported languages

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/todos#460]
[languages.yml](https://github.com/github-linguist/linguist/blob/cddf7476af4c95d1572956ffc5c0cb84f7e431c5/lib/linguist/languages.yml) in the GitHub linguist project has a good list of languages but I'll need to look up and register how strings and comments are written in each language.

Maybe having a similar `languages.yml` file and then deriving the scanner configuration from that would be the best way to maintain it. Right now the code is just [statically written](https://github.com/ianlewis/todos/blob/28bb5e97da5810ca00a4e028a5bce0d862d3b42a/internal/scanner/config.go) which may be a bit cumbersome.

### TIOBE Index

1. [x] Python
2. [x] C
3. [x] C++
4. [x] Java
5. [x] C#
6. [x] JavaScript
7. [x] Visual Basic (#1038)
8. [x] PHP
9. [x] SQL (#310)
10. [x] Assembly language (#122)
11. [x] Go
12. [ ] ~~Scratch~~ (Not a text based language)
13. [x] Delphi/Object Pascal (#1560)
14. [x] MATLAB (#1537)
15. [x] Swift
16. [x] Fortran (#1490)
17. [x] R (#332)
18. [x] Kotlin (#1209)
19. [x] Ruby
20. [x] Rust (#116)
21. [x] Classic Visual Basic (#1038)
22. [ ] SAS
23. [ ] Ad
24. [ ] COBOL
25. [ ] Prolog
26. [x] Lua (#98)
27. [x] Perl
28. [ ] Julia
29. [ ] D
30. [ ] (Visual) FoxPro
31. [ ] Dart
32. [x] Haskell (#317)
33. [x] Objective-C
34. [ ] Transact-SQL
35. [ ] Lisp
36. [ ] F#
37. [ ] GAMS
38. [x] Scala
39. [ ] ~~VBScript~~ ([Deprecated](https://en.wikipedia.org/wiki/VBScript))
40. [ ] Logo
41. [ ] PL/SQL
42. [x] Bash
43. [ ] CFML
44. [x] PowerShell (#1543)
45. [ ] Solidity
46. [ ] Scheme
47. [ ] ABAP
48. [ ] X++
49. [x] TypeScript
50. [ ] Awk

### Top 250 languages on GitHub

This is based on the BigQuery public data table. Many important file formats are missing from this (e.g. YAML, TOML, etc). I think this is because while they are in many many repos the data only includes the languages that make up a large % of the repo contents and config files are using just a small part.

- [x] JavaScript
- [x] Python
- [x] Java
- [x] PHP
- [x] Ruby
- [x] C++
- [x] HTML
- [x] C
- [x] CSS
- [x] C#
- [x] Shell
- [x] Go
- [x] Objective-C
- [x] Swift
- [x] TypeScript
- [x] Haskell (#317)
- [x] CoffeeScript (#702)
- [x] Scala
- [x] Clojure (#734)
- [x] Lua
- [x] Perl
- [x] R
- [x] Rust (#116)
- [x] ~~Jupyter Notebook~~ (JSON that doesn't support comments)
- [x] TeX (#766)
- [x] ~~Arduino~~ (C++)
- [x] Matlab (#1537)
- [x] PowerShell (#1543)
- [x] Erlang (#327)
- [x] Groovy (#784)
- [x] Makefile
- [x] Emacs Lisp (#798)
- [x] ~~VimL~~ (This is Vim Script)
- [x] Puppet (#883)
- [x] Kotlin (#1209)
- [x] Elixir (#1547)
- [ ] Julia
- [x] Vim script (#1541)
- [ ] Dart
- [x] Visual Basic  (#1038)
- [x] Assembly (#122)
- [ ] OCaml
- [ ] Common Lisp
- [ ] F#
- [ ] Processing
- [ ] ActionScript
- [ ] ApacheConf
- [ ] Pascal
- [ ] CMake
- [ ] Vue
- [x] Dockerfile
- [ ] XSLT
- [ ] D
- [ ] Haxe
- [ ] Scheme
- [ ] Batchfile
- [ ] Elm
- [ ] Eagle
- [ ] SCSS
- [ ] QML
- [ ] MATLAB
- [x] FORTRAN (#1490)
- [ ] Racket
- [ ] Verilog
- [ ] ASP
- [ ] VHDL
- [ ] Cuda
- [ ] Vala
- [ ] Crystal
- [x] Fortran (#1490)
- [x] HCL (#1592)
- [ ] Nginx
- [ ] Prolog
- [ ] OpenSCAD
- [ ] Groff
- [ ] ColdFusion
- [ ] PLpgSQL
- [ ] Tcl
- [ ] AutoHotkey
- [ ] PureScript
- [ ] PLSQL
- [ ] Mathematica
- [ ] KiCad
- [ ] Smarty
- [ ] Objective-C++
- [ ] Smalltalk
- [x] Vim Script (#1541)
- [ ] Perl6
- [ ] Apex
- [ ] SourcePawn
- [ ] SQF
- [ ] SaltStack
- [ ] BitBake
- [ ] AppleScript
- [ ] Logos
- [ ] LiveScript
- [ ] GLSL
- [ ] Roff
- [ ] PostScript
- [ ] Nimrod
- [ ] GDScript
- [ ] AutoIt
- [ ] DM
- [ ] IDL
- [ ] Coq
- [ ] OpenEdge ABL
- [ ] Ada
- [ ] Nim
- [x] XML
- [ ] LabVIEW
- [ ] Max
- [ ] Perl 6
- [ ] Handlebars
- [ ] SQLPL
- [ ] Web Ontology Language
- [ ] Pure Data
- [ ] Standard ML
- [ ] Squirrel
- [ ] SuperCollider
- [ ] Protocol Buffer
- [ ] Nix
- [ ] Jinja
- [ ] Stata
- [ ] Awk
- [ ] Xtend
- [ ] TSQL
- [ ] NSIS
- [ ] M
- [ ] M4
- [ ] SystemVerilog
- [ ] Hack
- [ ] API Blueprint
- [ ] LookML
- [ ] FreeMarker
- [ ] Game Maker Language
- [ ] XQuery
- [ ] Idris
- [ ] Forth
- [ ] DIGITAL Command Language
- [ ] Liquid
- [ ] Yacc
- [ ] Gettext Catalog
- [ ] Agda
- [ ] GAP
- [ ] GCC Machine Description
- [ ] AGS Script
- [ ] Less
- [ ] MoonScript
- [ ] BlitzBasic
- [ ] PAWN
- [ ] QMake
- [ ] ABAP
- [ ] CartoCSS
- [ ] nesC
- [ ] Scilab
- [ ] Cucumber
- [ ] Ceylon
- [ ] ANTLR
- [ ] Raku
- [ ] PureBasic
- [ ] NetLogo
- [ ] xBase
- [ ] Objective-J
- [ ] Gnuplot
- [ ] SAS
- [ ] Gosu
- [ ] ooc
- [ ] Delphi
- [x] Visual Basic .NET  (#1038)
- [ ] Gherkin
- [ ] Brainfuck
- [ ] Starlark
- [ ] LilyPond
- [ ] Monkey
- [ ] UnrealScript
- [ ] Lex
- [ ] Rebol
- [ ] Eiffel
- [ ] AMPL
- [ ] Inno Setup
- [ ] Rich Text Format
- [ ] Propeller Spin
- [ ] Xojo
- [x] SQL (#310)
- [ ] Mercury
- [ ] ShaderLab
- [ ] 1C Enterprise
- [ ] Diff
- [ ] Brightscript
- [ ] COBOL
- [ ] RobotFramework
- [ ] Modelica
- [ ] Dylan
- [ ] Isabelle
- [ ] RAML
- [ ] CLIPS
- [ ] KiCad Layout
- [ ] Bro
- [ ] LSL
- [ ] Io
- [ ] Lasso
- [ ] Hy
- [ ] Smali
- [ ] Bison
- [ ] LLVM
- [ ] Twig
- [x] VBA  (#1038)
- [ ] Pony
- [ ] Cython
- [ ] Frege
- [ ] DOT
- [ ] Ren'Py
- [ ] Pug
- [ ] AspectJ
- [ ] IGOR Pro
- [ ] MAXScript
- [ ] Thrift
- [ ] Vim Snippet
- [ ] J
- [ ] Papyrus
- [ ] G-code
- [ ] Sass
- [ ] Stylus
- [ ] EJS
- [ ] PigLatin
- [ ] VCL
- [ ] POV-Ray SDL
- [ ] SMT
- [ ] Augeas
- [ ] Mako
- [ ] Parrot
- [ ] HLSL
- [ ] Lean
- [ ] Jsonnet
- [ ] Pawn
- [ ] Component Pascal
- [ ] Uno
- [ ] Nunjucks
- [ ] Boo
- [ ] Slash
- [ ] Bluespec
- [ ] Nemerle
- [ ] Pan
- [ ] Clean
- [ ] Rascal
- [ ] Blade
- [ ] q
- [ ] ATS
- [ ] ChucK
- [ ] Inform 7

**Comment by ianlewis** [comment]
Leasot has a supported languages list: https://github.com/pgilad/leasot/blob/master/media/supported-languages.md

**Comment by ianlewis** [comment]
Need to rework languages so they each have their own parser to support idiosyncrasies in how some languages are parsed.

For example VimL uses quote characters (") for both strings and line comments. A parser would need to determine the difference between the two.

**Comment by ianlewis** [comment]
Will close once there are a total of 50 supported languages.

**Comment by ianlewis** [comment]
We now have 49 supported languages. I added issues for some remaining languages that I want to add support for.

Will go ahead and close this and add language support via other issues.
